export const types = {
  MEMBER_LOGIN_SUCCESS: "MEMBER_LOGIN_SUCCESS",
  MEMBER_LOGIN_FAIL: "MEMBER_LOGIN_FAIL",
  MEMBER_LOGOUT_SUCCESS: "MEMBER_LOGOUT_SUCCESS",
  MEMBER_LOGOUT_FAIL: "MEMBER_LOGOUT_FAIL",
  MEMBER_DETAILS_SUCCESS: "MEMBER_DETAILS_SUCCESS",
  MEMBER_DETAILS_FAIL: "MEMBER_DETAILS_FAIL",
  ALL_MEMBERS_DETAILS: "ALL_MEMBERS_DETAILS",
};
